version: '3'

services:

  postgres:
    image: 'postgres:latest'
    container_name: playlist-postgres
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    user: postgres 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playlist


  app:
    container_name: playlist-service
    build:
      context: .
      dockerfile: playlist-service.dockerfile
    ports:
      - '8080:8080'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=playlist sslmode=disable timezone=UTC connect_timeout=5"