version: '3'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playlist

  app:
    container_name: playlist-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: playlist-service.dockerfile
    ports:
      - '8080:8080'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres