// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Category struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	Features string `json:"features"`
}

type Dish struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	RestaurantID string  `json:"restaurantID"`
	Price        float64 `json:"price"`
	CuisineStyle string  `json:"cuisineStyle"`
	Ingredient   string  `json:"ingredient"`
	Comment      string  `json:"comment"`
}

type Playlist struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	CategoryCode string    `json:"categoryCode"`
	DietaryInfo  string    `json:"dietaryInfo"`
	Status       string    `json:"status"`
	StartDate    time.Time `json:"startDate"`
	EndDate      time.Time `json:"endDate"`
	Popularity   int32     `json:"popularity"`
}

type PlaylistDish struct {
	ID         string `json:"id"`
	DishID     string `json:"dishID"`
	PlaylistID string `json:"playlistID"`
}

type Restaurant struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	UnitNumber   string `json:"unitNumber"`
	AddressLine1 string `json:"addressLine1"`
	AddressLine2 string `json:"addressLine2"`
	PostalCode   int32  `json:"postalCode"`
}
