// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	Code     string         `json:"code"`
	Name     string         `json:"name"`
	Features sql.NullString `json:"features"`
}

type Dish struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	RestaurantID string         `json:"restaurantID"`
	Price        float64        `json:"price"`
	CuisineStyle sql.NullString `json:"cuisineStyle"`
	Ingredient   sql.NullString `json:"ingredient"`
	Comment      sql.NullString `json:"comment"`
	ServeTime    time.Time      `json:"serveTime"`
}

type Playlist struct {
	ID           string         `json:"id"`
	PlaylistName string         `json:"playlistName"`
	CategoryCode string         `json:"categoryCode"`
	Price        float64        `json:"price"`
	DietaryInfo  sql.NullString `json:"dietaryInfo"`
	Status       string         `json:"status"`
	StartDate    time.Time      `json:"startDate"`
	EndDate      time.Time      `json:"endDate"`
	Popularity   int32          `json:"popularity"`
}

type PlaylistDish struct {
	ID         int32  `json:"id"`
	DishID     string `json:"dishID"`
	PlaylistID string `json:"playlistID"`
}

type Restaurant struct {
	ID             string         `json:"id"`
	RestaurantName string         `json:"restaurantName"`
	UnitNumber     string         `json:"unitNumber"`
	AddressLine1   string         `json:"addressLine1"`
	AddressLine2   sql.NullString `json:"addressLine2"`
	PostalCode     sql.NullInt32  `json:"postalCode"`
}
